# Ejercicios Python 2

Resuelve cada ejercicio en su celda y añade las pruebas necesarias para comprobar que funciona correctamente. Indica en un comentario la dificultad encontrada (del 1 al 5).

In [1]:
# Función que recibe un array y devuelve otro eliminando sus duplicados (función y pruebas)
import numpy as np
def elimina_duplicados(array):
    array_unico = np.unique(array)
 
    return array_unico

darray = np.random.randint(1,25, (12))
print (darray)
print (elimina_duplicados(darray))

Lista_nombres = ["Alex", "Julia", "Martín", "Cristina", "Alex", "Manuel", "Clara", "Julia", "Pedro"]
narray = np.array(Lista_nombres)
# Lista_final = elimina_duplicados (Lista_entrada)
print (elimina_duplicados(narray))

# Dificultad encontrada: 4


[23 20 10 11 10 21 13  4 21 24 15 21]
[ 4 10 11 13 15 20 21 23 24]
['Alex' 'Clara' 'Cristina' 'Julia' 'Manuel' 'Martín' 'Pedro']


In [5]:
# ejercicios2.ipynb ejercicio 2 numpy
# Función que recibe una matriz y devuelve otra eliminando sus duplicados
import numpy as np

def elimina_duplicados(array):
    lista_paso=[]
    f_array = np.full((array.shape), np.nan)
    for x in range(array.shape[0]):
        for y in range(array.shape[1]):
            if array[x,y] not in lista_paso:
                f_array[x,y] = array[x,y]
                lista_paso.append(array[x,y])
    
    return f_array
                
   


matriz = [[8, 14, -6], 
          [8, 5, -3], 
          [-11,3,8]]
narray = np.array (matriz)
print (elimina_duplicados (narray))

al_array = np.random.randint (20,size=(5,5))
print (elimina_duplicados (al_array))

# Dificultad encontrada: 4

[[  8.  14.  -6.]
 [ nan   5.  -3.]
 [-11.   3.  nan]]
[[ 6.  3. 13. 12. 15.]
 [ 1.  5. nan 17. 11.]
 [nan nan  8.  0. 16.]
 [ 9. nan nan 10. nan]
 [19. nan nan 14.  7.]]


In [8]:
# ejercicios2.ipynb ejercicio 3 numpy
# Función que recibe un array y devuelve un diccionario con el número de veces que aparece cada elemento 
# (las claves del diccionario deben ser los elementos de la lista y los valores deben ser 
# el número de veces que aparece dicho elemento en la lista)

import numpy as np
def list_dic(array):
    gen = dict((x, np.count_nonzero(array == x)) for x in array)
    # gen = {} comentada la funcion en formato no comprehensivo
    # for x in array:
    #     gen[x] = np.count_nonzero(array == x)
    return gen

al_array = np.random.randint(21, size=25)
print (al_array)
print (list_dic(al_array))

# Dificultad encontrada: 4

[ 4 13  5 13  2  6 19  6 10  9 14 20  8  5  4  3  6  7  9  3 14  6  9 17
 20]
{4: 2, 13: 2, 5: 2, 2: 1, 6: 4, 19: 1, 10: 1, 9: 3, 14: 2, 20: 2, 8: 1, 3: 2, 7: 1, 17: 1}


In [9]:
# ejercicios2.ipynb ejercicio 4
# Función que recibe dos matrices cuadradas (NxN) y devuelve una tercera matriz que contiene el valor 1 en las posiciones en que el valor de A y B coinciden 
# y 0 en caso contrario. Comprueba dimensiones de la matriz y ajusta el tamaño de la matriz resultante.

import numpy as np

def valores_iguales_matriz(matriz1, matriz2):
    if matriz1.shape != matriz2.shape or matriz1.shape[0] != matriz1.shape[1]:
        print ("El par de matrices no es válido, introduce dos matrices cuadradas iguales por favor. ")
    mat_final = matriz1 == matriz2
    mat_final = 1*mat_final
    
    return mat_final
    
matr1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Matriz 3x3
matr2 = [[1, 5, 6], [7, 5, 9], [1, 2, 9]] # Matriz 3x3
mat1 = np.array (matr1)
mat2 = np.array (matr2)
print ("Matriz 1\n", mat1 , "\nMatriz 2\n", mat2 , " \nMatriz comparacion \n" , valores_iguales_matriz(mat1, mat2))

mat3 = np.random.randint(5,size=(4,4))
mat4 = np.random.randint(5,size=(4,4))
print ("Matriz 3\n", mat3 , "\nMatriz 4\n", mat4 , " \nMatriz comparacion \n" , valores_iguales_matriz(mat3, mat4))
 

# Dificultad encontrada: 4


Matriz 1
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Matriz 2
 [[1 5 6]
 [7 5 9]
 [1 2 9]]  
Matriz comparacion 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matriz 3
 [[0 1 0 0]
 [1 4 3 1]
 [0 0 4 4]
 [0 1 1 0]] 
Matriz 4
 [[2 1 2 4]
 [1 3 3 2]
 [2 4 1 3]
 [3 2 1 1]]  
Matriz comparacion 
 [[0 1 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 1 0]]


In [3]:
# ejercicios2.ipynb ejercicio 5 numpy

# Función que recibe una matriz y busca sus puntos de silla (mínimo de su fila y máximo de su columna o viceversa). 
# Debe devolver una lista de tuplas con las coordenadas de los puntos de silla.

import numpy as np

def puntos_silla(matriz):
    lista_puntos = []
    for x in range(matriz.shape[0]):
        for y in range(matriz.shape[1]):
            if matriz [x,y] == np.min(matriz [:,y]) == np.max(matriz [x]) or matriz [x,y] == np.max(matriz [:,y]) == np.min(matriz [x]):
                lista_puntos.append((x,y))
          
    return lista_puntos
    
matr1 = [[10,20,5],[40,10,30],[60,30,50]]
mat1 = np.array(matr1)
print (mat1, "\n" , "Puntos de silla" , puntos_silla(mat1))
matr2 = [[1,2,3],[4,5,6],[7,8,9]]
mat2 = np.array(matr2)
print ( mat2, "\n", "Puntos de silla" , puntos_silla(mat2))
mat3 = np.random.randint(16, size=(4,4))
print (mat3 , "\n", "Puntos de silla" , puntos_silla(mat3))

# Dificultad encontrada: 5


[[10 20  5]
 [40 10 30]
 [60 30 50]] 
 Puntos de silla [(2, 1)]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Puntos de silla [(0, 2), (2, 0)]
[[ 7  9  1 11]
 [ 8  1 13  4]
 [14 14 13 12]
 [ 3  3  5 11]] 
 Puntos de silla [(2, 3)]


## 

## 